// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsz_9yiA5EfZT-wS_DNr8QWh5FzcbY9gs',
    appId: '1:242787662957:web:4b8dc687caf8e344155364',
    messagingSenderId: '242787662957',
    projectId: 'tiktok-clone-prac',
    authDomain: 'tiktok-clone-prac.firebaseapp.com',
    storageBucket: 'tiktok-clone-prac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7XreOwnJatfnPJjYrsX_RYsHn0EbX9M',
    appId: '1:242787662957:android:d6e02d52221d117f155364',
    messagingSenderId: '242787662957',
    projectId: 'tiktok-clone-prac',
    storageBucket: 'tiktok-clone-prac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfDRXvhnfG7MFqiFLXIaWT093qYVPvPSk',
    appId: '1:242787662957:ios:856738a972312aee155364',
    messagingSenderId: '242787662957',
    projectId: 'tiktok-clone-prac',
    storageBucket: 'tiktok-clone-prac.appspot.com',
    iosClientId: '242787662957-goc17d080mcrrqmv31i0uatsqpm0jg35.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfDRXvhnfG7MFqiFLXIaWT093qYVPvPSk',
    appId: '1:242787662957:ios:856738a972312aee155364',
    messagingSenderId: '242787662957',
    projectId: 'tiktok-clone-prac',
    storageBucket: 'tiktok-clone-prac.appspot.com',
    iosClientId: '242787662957-goc17d080mcrrqmv31i0uatsqpm0jg35.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
